var a = new Audio(); a.src = "audio/a.mp3"; function play_a() { a.play(); }
var o = new Audio(); o.src = "audio/o.mp3"; function play_o() { o.play(); }
var oh = new Audio(); oh.src = "audio/oh.mp3"; function play_oh() { oh.play(); }
var u = new Audio(); u.src = "audio/u.mp3"; function play_u() { u.play(); }
var uh = new Audio(); uh.src = "audio/uh.mp3"; function play_uh() { uh.play(); }
var i = new Audio(); i.src = "audio/i.mp3"; function play_i() { i.play(); }
var eh1 = new Audio(); eh1.src = "audio/eh1.mp3"; function play_eh1() { eh1.play(); }
var eh2 = new Audio(); eh2.src = "audio/eh2.mp3"; function play_eh2() { eh2.play(); }
var ia = new Audio(); ia.src = "audio/ia.mp3"; function play_ia() { ia.play(); }
var ioh = new Audio(); ioh.src = "audio/ioh.mp3"; function play_ioh() { ioh.play(); }
var io = new Audio(); io.src = "audio/io.mp3"; function play_io() { io.play(); }
var iu = new Audio(); iu.src = "audio/iu.mp3"; function play_iu() { iu.play(); }
var ieh1 = new Audio(); ieh1.src = "audio/ieh1.mp3"; function play_ieh1() { ieh1.play(); }
var ieh2 = new Audio(); ieh2.src = "audio/ieh2.mp3"; function play_ieh2() { ieh2.play(); }