var a = new Audio(); a.src = "audio/a.mp3"; function play_a() { a.play(); }
var o = new Audio(); o.src = "audio/o.mp3"; function play_o() { o.play(); }
var oh = new Audio(); oh.src = "audio/oh.mp3"; function play_oh() { oh.play(); }
var u = new Audio(); u.src = "audio/u.mp3"; function play_u() { u.play(); }
var uh = new Audio(); uh.src = "audio/uh.mp3"; function play_uh() { uh.play(); }
var i = new Audio(); i.src = "audio/i.mp3"; function play_i() { i.play(); }
var eh1 = new Audio(); eh1.src = "audio/eh1.mp3"; function play_eh1() { eh1.play(); }
var eh2 = new Audio(); eh2.src = "audio/eh2.mp3"; function play_eh2() { eh2.play(); }
var ia = new Audio(); ia.src = "audio/ia.mp3"; function play_ia() { ia.play(); }
var ioh = new Audio(); ioh.src = "audio/ioh.mp3"; function play_ioh() { ioh.play(); }
var io = new Audio(); io.src = "audio/io.mp3"; function play_io() { io.play(); }
var iu = new Audio(); iu.src = "audio/iu.mp3"; function play_iu() { iu.play(); }
var ieh1 = new Audio(); ieh1.src = "audio/ieh1.mp3"; function play_ieh1() { ieh1.play(); }
var ieh2 = new Audio(); ieh2.src = "audio/ieh2.mp3"; function play_ieh2() { ieh2.play(); }
var ua = new Audio(); ua.src = "audio/ua.mp3"; function play_ua() { ua.play(); }
var ue = new Audio(); ue.src = "audio/ue.mp3"; function play_ue() { ue.play(); }
var ue2 = new Audio(); ue2.src = "audio/ue2.mp3"; function play_ue2() { ue2.play(); }
var uoh = new Audio(); uoh.src = "audio/uoh.mp3"; function play_uoh() { uoh.play(); }
var ui = new Audio(); ui.src = "audio/ui.mp3"; function play_ui() { ui.play(); }
var uhi = new Audio(); uhi.src = "audio/uhi.mp3"; function play_uhi() { uhi.play(); }
var k = new Audio(); k.src = "audio/k.mp3"; function play_k() { k.play(); }
var kk = new Audio(); kk.src = "audio/kk.mp3"; function play_kk() { kk.play(); }
var kh = new Audio(); kh.src = "audio/kh.mp3"; function play_kh() { kh.play(); }
var n = new Audio(); n.src = "audio/n.mp3"; function play_n() { n.play(); }
var t = new Audio(); t.src = "audio/t.mp3"; function play_t() { t.play(); }
var tt = new Audio(); tt.src = "audio/tt.mp3"; function play_tt() { tt.play(); }
var th = new Audio(); th.src = "audio/th.mp3"; function play_th() { th.play(); }
var r_l = new Audio(); r_l.src = "audio/r_l.mp3"; function play_r_l() { r_l.play(); }
var m = new Audio(); m.src = "audio/m.mp3"; function play_m() { m.play(); }
var b_p = new Audio(); b_p.src = "audio/b_p.mp3"; function play_b_p() { b_p.play(); }
var pp = new Audio(); pp.src = "audio/pp.mp3"; function play_pp() { pp.play(); }
var ph = new Audio(); ph.src = "audio/ph.mp3"; function play_ph() { ph.play(); }
var s = new Audio(); s.src = "audio/s.mp3"; function play_s() { s.play(); }
var ss = new Audio(); ss.src = "audio/ss.mp3"; function play_ss() { ss.play(); }
var ng = new Audio(); ng.src = "audio/ng.mp3"; function play_ng() { ng.play(); }
var ch_dj = new Audio(); ch_dj.src = "audio/ch_dj.mp3"; function play_ch_dj() { ch_dj.play(); }
var ch = new Audio(); ch.src = "audio/ch.mp3"; function play_ch() { ch.play(); }
var h = new Audio(); h.src = "audio/h.mp3"; function play_h() { h.play(); }
var jj = new Audio(); jj.src = "audio/jj.mp3"; function play_jj() { jj.play(); }

